function _panic() {
  >&2 echo "$1"
  exit 1
}

export ROLE_NAME=$(whoami)-extension-demo
export BUFFERED_FUNCTION_NAME=$(whoami)-signalfx-extension-demo-buffered
export REAL_TIME_FUNCTION_NAME=$(whoami)-signalfx-extension-demo-realm-time

export FUNCTION_RUNTIME=${FUNCTION_RUNTIME:-nodejs12.x}
export FUNCTION_CODE=${FUNCTION_CODE:-UEsDBBQAAAAIAJRsYVJ3m87PcAAAAHgAAAAIABwAaW5kZXguanNVVAkAA9jfPGDZ3zxgdXgLAAEE9QEAAAQUAAAAS60oyC8qKdbLSMxLyUktUrBVSCyuzEtW0NBUsLVTqOZSUChKLSktygMzFRSKSxJLSoud81NSrRSMDAx0wIJJ+SmVVgpewf5+esUlRZl56ZlplRrqHqk5OfkKaUX5uQo+iblJKYmK6pog9bXWXEAEAFBLAQIeAxQAAAAIAJRsYVJ3m87PcAAAAHgAAAAIABgAAAAAAAEAAACkgQAAAABpbmRleC5qc1VUBQAD2N88YHV4CwABBPUBAAAEFAAAAFBLBQYAAAAAAQABAE4AAACyAAAAAAA=}
